# [manager]
# prepend_keymap = [
#   { on = ["<C-k>"],        run = "seek -5", desc = "Seek up 5 units in the preview" },
#   { on = ["<C-j>"],        run = "seek 5",  desc = "Seek down 5 units in the preview" },
# ]

[[manager.prepend_keymap]]
# on = ["<C-k>"]
on = ["["]
# on = ["<S-h>"]
run = "seek -5"
desc = "Seek up 5 units in the preview"

[[manager.prepend_keymap]]
# on = ["<C-j>"]
on = ["]"]
# on = ["<S-l>"]
run = "seek 5"
desc = "Seek down 5 units in the preview"

